# Generated by Django 5.2.7 on 2025-10-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('attendance_rate', models.FloatField()),
                ('study_hours_per_week', models.FloatField()),
                ('previous_grade', models.FloatField()),
                ('extracurricular_activities', models.BooleanField(default=False)),
                ('parental_support', models.CharField(max_length=10)),
                ('online_classes_taken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_result', models.CharField(max_length=4)),
                ('confidence_score', models.FloatField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('survey_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.surveyresponse')),
            ],
        ),
    ]
